### ISSUE TITLE
Unable to run on El Capitan

### ISSUE THREAD

**Issue by sohayb** [JiriTrecak/Laurine#10]
I'm unable to run the package under El Capitan :(
getting this error:
````
<unknown>:0: error: no such file or directory: 'LaurineGenerator.swift'
````

**Comment by JiriTrecak** [comment]
Hey sohayb,

I just tried to run it on El Capitan and it seems that it works for me, from both downloaded script and brew (are you sure you are trying it in folder where it is if you have it downloaded? :)) 

Aren't you trying to do 

    swift LaurineGenerator.swift ? 

Because if downloaded from brew, there is no need to write "swift" at the beginning of the command - it won't work and it will throw the exact error as I just tried:

    X:~ jiritrecak$ swift LaurineGenerator.swift
    <unknown>:0: error: no such file or directory: 'LaurineGenerator.swift'

Hope it helps!
Have a nice day

Jiri

**Comment by sohayb** [comment]
Cool, it worked! Now the command runs smoothly, except there's nothing generated :(
Running
````
LaurineGenerator.swift -i Localizable.strings -c -o Localizations.swift
````

**Comment by JiriTrecak** [comment]
Make sure you are in the folder where the "localizable.strings" file actually is (> cd path_to_loc.strings), the logging of the errors in the command line is coming in future version (currently, it will only tell you that those files do not exists if you run it from xcode.

**Comment by sohayb** [comment]
This is embarrassing :) there was a leading space in the file name! 
Thanks for your help.

**Comment by JiriTrecak** [comment]
You are most welcome. Enjoy the tool!
