### ISSUE TITLE
Repeated usage

### ISSUE THREAD

**Issue by victor** [JiriTrecak/Laurine#12]
If I understand the usage correctly, you need to remove instances of `NSLocalizedString` and its variations from your code, and then replace them with the corresponding generated `Localizations.…` properties and variables.

But then, this means that `genstrings` command won't be able to extract these strings again, as it won't find them. How is then further maintenance of `Localizable.strings` supposed to happen?

What happens if a string is no longer used in the code? it will live forever in `Localizable.strings` and `Localizations.swift` unless manually removed, is that correct?

**Comment by JiriTrecak** [comment]
Hello Victor, 

Yes, you are absolutely correct with your understanding. Thought, I'd like to add two things that come from my experience (and you might have different one, but here is my piece):

Having keys / values in code is terrible when building huge projects. It is not on one place and therefore maintenance is hell. Also, it goes against usual paradigms of other languages (see android, where you cannot even write string into code, you have to define to through XML).

Second thing is that by having plain keys on different places in the application, usually those will end up beign in different formats (like "Profile.NavigationBar.X" and somewhere else you will find "Main Menu - Something"). 

This is especially hard to control when you have more people building one application. Also, it present problems with source control as the changes happen on many places at ones, you are changing basically whole files..

Personally, I think that genstrings tool has no place in Swift, because swift allows you to strongly type almost everything and Laurine (or for Storyboards - Natalie) is prime example of this.

I find this workflow the best:

- Create key / value in en.proj/.strings
- Add NSLocalizedString to code (or with Laurine, cmd+B and then add code)
- Once enough changes has been made or you want to translate to different language, upload to CrowdIn, and import remaining translations

Hope this gives you some insight how, and why :)

Have a nice day!

Jiri

**Comment by JiriTrecak** [comment]
As for removing NSLocalizedString with actual code, converter tool is coming probably within the month, that will do that for you (but it is quite complicated, so no promises on date yet.)

**Comment by victor** [comment]
Thanks Jiri,

 yes I'm aware of the maintenance nightmare of using string literals within the code, that's why I have all of them as constants/enums in a centralized file. But I could not use that approach for localization, as `genstrings` is confused when not using actual strings.

 I'm thinking I can always write code using `NSLocalizedString` until it is working and tested, and then run `genstrings` with the `-a` modifier to append to the existing file, and then replace the calls to `NSLocalizedString` with the Laurine-generated properties.
