### ISSUE TITLE
Compiled Script

### ISSUE THREAD

**Issue by fabb** [JiriTrecak/Laurine#30]
Running `LaurineGenerator.swift` in the run phase takes about 5 seconds with my localization file (containing 460 strings).

When first compiling the script to an executable, the generation time only takes 0.25 seconds.

I know in the example project, the output is only generated if existing output is not newer than the localization input file. For the sake of having a clean and reproducible build, I prefer to skip that check and delete the generated files every time before running the script.

How could this project provide binaries?
- Comparing to https://github.com/puls/objc-codegenutils this repo could contain an additional Xcode project for generating the binary
- A simple script could be added to execute `xcrun -sdk macosx swiftc LaurineGenerator.swift -o LaurineGenerator`
- [Swift Package Manager](https://github.com/apple/swift-package-manager) could be used

What do you think?

**Comment by JiriTrecak** [comment]
Makes sense - though currently, I am trying to finish functionality that I promised while ago and because of my startup I just did not have time to do - but I am finally getting shiz done. Once those things are in, I think we could do something like this - if you are up for it, I am definitely open to PRs for this, though I would probably do completely different branch.

As for the library generation, I think the problem will be forwarding events to it from the command line. I will have to think about it. There might be class that imports compiled library and would serve as a facade, but that would not help speed much as it would still have to be compiled. Honestly I never did it this way, so more research is definitely needed.

As for SPM, it would be definitely a solution - but not in current state, they are still changing great portions of the core and a lot of functionality is missing, and what we need I think is still not even possible (maybe it is?)

Anyway, this is more for later, once I have all the functionality done ; Plurals, gender etc. and some additional fixes are needed first, those are more of a things for convenience. For now, I would suggest using the shell script with new check instead.

Thank you and have a nice day
JT
