### ISSUE TITLE
Support for dictionaries

### ISSUE THREAD

**Issue by deville** [JiriTrecak/Laurine#32]
I need to map error codes to localized strings which currently does not seem to be possible with Laurine (or am I missing something?)

I would like to be able to write something like
```
let errorMessage = Foo.Bar.ErrorCodes(100500)
```
or 
```
let errorMessage = Foo.Bar.ErrorCodes[100500]
```

**Comment by JiriTrecak** [comment]
Hello, unfortunately, this is not possible at the moment. This might become possible once I am done with plurals because they will have something similar, but it is not ready yet.

Have a great day

Jiri

**Comment by JiriTrecak** [comment]
Hey Deville, 

after few solid hours of investigation and thinking, I decided that we cannot really support something like this. 
The problem is not that it would not be possible to do, but it would present some special syntax to laurine that is not supported by native localization functionality of the iOS/OSX, therefore requiring people to learn something new and present something that can potentially break their project once they don't won't to use laurine anymore.

If you come up with the idea about how to do something like this while using ONLY the functionality provided natively (ie. key naming etc.), then please open new issue and we can discuss further.

Sincerely, 

Jiri
