### ISSUE TITLE
Improvement Request

### ISSUE THREAD

**Issue by ed-mejia** [JiriTrecak/Laurine#7]
Hi, 

Regarding Git the script becomes a little annoying because of the timestamp added to the documentation header:

//
// Autogenerated by Laurine - by Jiri Trecak ( http://jiritrecak.com, @jiritrecak )
// Do not change this file manually!
//
// **2015-12-14 at 5:48 PM**
//

That makes the file to be included on every commit just because of the date time update.

I think there are two options to deal with this:
1) Do not add it so if there are no updates to the file It will not record anything to git
2) The best one could be check the OUTPUT_PATH Localization.swift file modification date and compare it to SOURCE_PATH Localizable.strings e.g:

if Localizable.strings.modificationDate > Localization.swift.modificationDate {
do rebuild
} else {
ignore since there is no changes
}

What do you think?

**Comment by JiriTrecak** [comment]
Hey Edinson, 
thank you for your feedback!

I have to say I already encountered exactly same thing. The issue actually runs deeper - if you are not working alone, it becomes major hinderance. There is also second problem with script that I resolved over the weekend - I thought it might be good idea to lock that file, unfortunately git then just refuses to cooperate with you completely when you need, for example, reset that file! and this goes back to each-time-regenerating file, because sometimes it goes to situation where you just can't do anything with it - reset, stash, reverse.. oh well.

So yes, I completely agree this should be changed. I think the timestamp has some meaning there, I will change the bash script so it checks and generates only if needed and add it to readme / example. You can modify following to fix it (in build phase):

    if [ "$OUTPUT_PATH" -ot "$SOURCE_PATH" ]; then
        "$LAURINE_PATH" -i "$SOURCE_PATH" -o "$OUTPUT_PATH"
    fi

Have a nice day!

**Comment by ed-mejia** [comment]
Cool adding that snippet seems to do the trick, it's much better now.

Thanks!

**Comment by JiriTrecak** [comment]
Glad I could help!

**Comment by richardbuckle** [comment]
Hi guys,

Firstly, I would like to make you aware of the options in Xcode for specifying the inputs and outputs that it uses for dependency testing. Screenshot below. These reduce unnecessary invocations of the build step.

![screen shot 2015-12-15 at 02 30 35](https://cloud.githubusercontent.com/assets/227024/11800418/2b2cfb1c-a2d4-11e5-9c3c-d451b3e94df2.png)

Secondly, I *very* strongly disagree that any sort of timestamp should exist in the source file. This is not the first time that I have seen redundant timestamps cause churn in the VCS.

The timestamp is metadata and I believe that such meta belongs only in the VCS, not in the file content.

**Comment by JiriTrecak** [comment]
Hey Richard

I know about the first option ; I considered it and realized, that while we might know, not many people know - there is nothing preventing you to modify that script on your own - that is why it is just example, right. My focus is to create something that is so easy to use, that you don't have to think about - sure, might seem like small change, but ctrl+c with everything still seem more viable.

As for the second question, after considering all pros and cons, I have to agree with you - metadata such as this should be governed only by VCS, if the date would be date of creation (as XCode does it) that would probably be okay - but that is also pointless to do. I will be changing the generator so it omits the date altogether and I will keep the script as we decided earlier due to simple fact that it is easy to copy paste. I might add more options in the future, I am considering ways how to make it easy using cocoapods anyway.

Thank you so much for your support.
